# Generated by Django 4.1.7 on 2023-04-01 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=200)),
                ('año', models.CharField(max_length=200)),
                ('observaciones', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('id_tipo_Auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.tipoauto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_nacional', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=200)),
                ('apelllido', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.genero')),
            ],
        ),
        migrations.CreateModel(
            name='AutoColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('id_Auto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.auto')),
                ('id_Color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.color')),
            ],
        ),
        migrations.AddField(
            model_name='auto',
            name='id_estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.estado'),
        ),
        migrations.AddField(
            model_name='auto',
            name='id_marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.marca'),
        ),
        migrations.AddField(
            model_name='auto',
            name='id_modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.modelo'),
        ),
        migrations.AddField(
            model_name='auto',
            name='id_tipo_Auto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapi.tipoauto'),
        ),
    ]
